config/routes.rb
Rails.application.routes.draw do
    root 'hello#index'
    devise_for :accounts
  resources :studies
  resources :board_messages
  resources :board_users
  resources :hello
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board_message.rb
class BoardMessage < ApplicationRecord
    belongs_to :board_user

    validates :content, presence: {message: 'は、必須項目です。'}
end

app/models/board_user.rb
class BoardUser < ApplicationRecord
    belongs_to :account
    has_many :board_message

    validates :nickname, presence: {message:'は、必須項目です。'}
end

app/models/study.rb
class Study < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/board_messages_controller.rb
class BoardMessagesController < ApplicationController
  before_action :set_board_message, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!
  layout 'board_messages'

  # GET /board_messages
  # GET /board_messages.json
  def index
    @board_messages = BoardMessage.page(params[:page]).order('created_at desc')
    users = BoardUser.where('account_id == ?', current_account.id)[0]
    if users == nil
      user = BoardUser.new
      user.account_id = current_account.id
      user.nickname = '<<no name>>'
      user.save
      users = BoardUser.where 'account_id == ?', current_account.id
    end
    @board_user = users
    @board_messages = BoardMessage.new
    @board_messages.board_user_id = @board_user.id
  end

  # GET /board_messages/1
  # GET /board_messages/1.json
  def show
    redirect_to '/board_messages'
  end

  # GET /board_messages/new
  def new
    redirect_to '/board_messages'
  end

  # GET /board_messages/1/edit
  def edit
    redirect_to '/board_messages'
  end

  # POST /board_messages
  # POST /board_messages.json
  def create
    @board_message = BoardMessage.page([params[:page]]).order('created_at desc')
    @board_message = BoardMessage.new(board_message_params)
    @board_user = BoardMessage.where('account_id == ?', current_account.id)[0]
    respond_to do |format|
      if @board_message.save
        format.html { redirect_to '/board_messages'}
        format.json { render :show, status: :created, location: @board_messages }
      else
        format.html { render :index}
        format.json { render json: @board_message.errors,status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /board_messages/1
  # PATCH/PUT /board_messages/1.json
  def update
    redirect_to '/board_messages'
  end

  # DELETE /board_messages/1
  # DELETE /board_messages/1.json
  def destroy
    redirect_to '/board_messages'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board_message
      @board_message = BoardMessage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_message_params
      params.require(:board_message).permit(:content, :board_user_id)
    end
end

app/controllers/board_users_controller.rb
class BoardUsersController < ApplicationController
  before_action :set_board_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account:

  # GET /board_users
  # GET /board_users.json
  def index
    users = BoardUser.where 'account_id == ?',current_account.id
    if users[0] == nil
      user = BoardUser.new
      user.account_id = current_account.id
      user.nickname = '<<no name'
      user.save
      users = BoardUser.where 'account_id == ?', current_account.id
    end
    @board_user = users[0]
  end

  # GET /board_users/1
  # GET /board_users/1.json
  def show
    @board_user = BoardUser.find params[:id]
  end

  # GET /board_users/new
  def new
    redirect_to '/board_messages'
  end

  # GET /board_users/1/edit
  def edit
    redirect_to '/board_messages'
  end

  # POST /board_users
  # POST /board_users.json
  def create
    redirect_to '/board_messages'
  end

  # PATCH/PUT /board_users/1
  # PATCH/PUT /board_users/1.json
  def update
    respond_to do |format|
      if @board_user.update(board_user_params)
        format.html { redirect_to '/board_messages' }
        format.json { render :show, status: :ok, location: @board_user }
      else
        format.html { render :index }
        format.json { render json: @board_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /board_users/1
  # DELETE /board_users/1.json
  def destroy
    redirect_to '/board_messages'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board_user
      @board_user = BoardUser.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_user_params
      params.require(:board_user).permit(:nickname, :account_id, :memo)
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end

  def login_check
  end
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController
  before_action :set_study, only: [:show, :edit, :update, :destroy]

  # GET /studies
  # GET /studies.json
  def index
    @studies = Study.all.order 'date asc'
  end

  # GET /studies/1
  # GET /studies/1.json
  def show
    redirect_to '/studies#index'
  end

  # GET /studies/new
  def new
    if request.post?
      Study.create(study_params)
      goback
    else
    @study = Study.new
    end
  end

  # GET /studies/1/edit
  def edit
    @study = Study.find(params[:id])
    if request.patch?
      @study.update(study_params)
    end
  end

  # POST /studies
  # POST /studies.json
  def create
    @study = Study.new(study_params)

    respond_to do |format|
      if @study.save
        format.html { redirect_to @study, notice: '新規内容が追加されました。' }
        format.json { render :show, status: :created, location: @study }
      else
        format.html { render :new }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /studies/1
  # PATCH/PUT /studies/1.json
  def update
    respond_to do |format|
      if @study.update(study_params)
        format.html { redirect_to @study, notice: '変更内容が更新されました。' }
        format.json { render :show, status: :ok, location: @study }
      else
        format.html { render :edit }
        format.json { render json: @study.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studies/1
  # DELETE /studies/1.json
  def destroy
    @study.destroy
    respond_to do |format|
      format.html { redirect_to studies_url, notice: '指定された内容が削除されました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_study
      @study = Study.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def study_params
      params.require(:study).permit(:date, :title, :memo, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_messages_helper.rb
module BoardMessagesHelper
end

app/helpers/board_users_helper.rb
module BoardUsersHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/studies_helper.rb
module StudiesHelper
end

app/views/board_messages/_form.html.erb
<%= form_with(model: board_message) do |form| %>
  <% if board_message.errors.any? %>
    <div id="error_explanation">
      <h2 class="h4"><%= pluralize(board_message.errors.count, "error") %> prohibited this board_message from being saved:</h2>

      <ul>
        <% board_message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :board_user_id %>
    <div class="border p-1"><%= @board_user.nickname %></div>
    <%= form.hidden_field :board_user_id %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.number_area :content, class:'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/board_messages/board_messages.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Board Messages</title>
        <% csrf_meta_tags %>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css">
        <%= stylesheet_link_tag 'application','data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application','data-turbolinks-track': 'reload' %>
    </head>

    <body class="container">
        <%= yield %>
        <div class="mt-5 text-center small text-secondary border-top border-secondary">2020 SYODA-Tuyano.</div>
    </body>
</html>

app/views/board_messages/edit.html.erb
<h1>Editing Board Message</h1>

<%= render 'form', board_message: @board_message %>

<%= link_to 'Show', @board_message %> |
<%= link_to 'Back', board_messages_path %>

app/views/board_messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="display-4 text-primary">Message Board</h1>
<%= render 'form', board_message: @board_message %>
<p><%= link_to 'go home >>', controller: :board_users %></p>
<hr>
<h2 class="h4">※Posted Messages.</h2>
<table class="table">
  <thead>
    <tr>
      <th>Content</th>
      <th width="200px">User</th>
    </tr>
  </thead>

  <tbody>
    <% @board_messages.each do |board_message| %>
      <tr>
        <td><%= board_message.content %></td>
        <td><%= link_to board_message.board_user.nickname,controller: :board_users,action: :show, id:board_message.board_user_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<div><%= paginate @board_messages %></div>
<hr>
<div>copyright SYODA</div>

app/views/board_messages/new.html.erb
<h1>New Board Message</h1>

<%= render 'form', board_message: @board_message %>

<%= link_to 'Back', board_messages_path %>

app/views/board_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @board_message.content %>
</p>

<p>
  <strong>Board user:</strong>
  <%= @board_message.board_user_id %>
</p>

<%= link_to 'Edit', edit_board_message_path(@board_message) %> |
<%= link_to 'Back', board_messages_path %>

app/views/board_users/_form.html.erb
<%= form_with(model: board_user) do |form| %>
  <% if board_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board_user.errors.count, "error") %> prohibited this board_user from being saved:</h2>

      <ul>
        <% board_user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :account_id %>

  <div class="form-group">
    <%= form.label :nickname %>
    <%= form.text_field :nickname, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :account_id %>
    <div class="border p-1"><%= @board_user.account_id %></div>
    <%= form.hidden_field :account_id %>
  </div>

  <div class="form-group">
    <%= form.label :memo %>
    <%= form.text_area :memo, class:'form-control' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/board_users/edit.html.erb
<h1>Editing Board User</h1>

<%= render 'form', board_user: @board_user %>

<%= link_to 'Show', @board_user %> |
<%= link_to 'Back', board_users_path %>

app/views/board_users/index.html.erb
<h1 class="display-4 text-primary">User Home</h1>
<h2 class="h4">※<%= @board_user.account.email %>さんの設定</h2>
<%= render 'form', board_user: @board_user %>
<hr>
<p><%= link_to '<< go back', controller: :board_messages %></p>

<hr>
<div>copyright SYODA-Tuyano 2020.</div>

app/views/board_users/new.html.erb
<h1>New Board User</h1>

<%= render 'form', board_user: @board_user %>

<%= link_to 'Back', board_users_path %>

app/views/board_users/show.html.erb
<h1 class="display-4 text-primary"><%= @board_user.nickname %></h1>

<table class="table">
<tr>
  <h1>Nickname</h1>
  <td><%= @board_user.nickname %></td>
</tr>

<tr>
  <th>Id</th>
  <td><%= @board_user.id %></td>
</tr>

<tr>
  <th>Created at</th>
  <td><%= @board_user.created at %></td>
</tr>

<tr>
  <th>Memo</th>
  <%= @board_user.memo %>
</tr>
</table>

<hr>
<%= link_to '<<Back', controller: :board_messages %>
<hr>
<div>copyright SYODA-Tuyano 2020.</div>

app/views/hello/index.html.erb
<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
         <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>RubyでRails</h1>
            <span class="subheading">こういうオフィスで仕事がしたい</span>
          </div>
        </div>
      </div>
    </div>
</header>

app/views/hello/login_check.html.erb
<h1>Hello#login_check</h1>
<p>Find me in app/views/hello/login_check.html.erb</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="index.html">Rabbit Times</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/hello">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/studies">学習状況</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/board_messages">BoardMessages</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/accounts">ログイン</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDeviseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    
  </body>
</html>

app/views/studies/_form.html.erb
<%= form_with(model: study) do |form| %>
  <% if study.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(study.errors.count, "error") %> prohibited this study from being saved:</h2>

      <ul>
        <% study.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_area :memo %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/studies/edit.html.erb
<h1 class="display-4 text-primary">設定した学習内容を変更する</h1>

<%= form_for(@study, rul:{controller:'studies',action:'edit'}) do |form| %>
    <div class="form-group">
        <label for="date">日付</title>
        <%= form.text_field :date,{class:"form-control"} %>
    </div>
    <div class="form-group">
        <label for="title">学習した内容</title>
        <%= form.text_field :title,{class:"form-control"} %>
    </div>
    <div class="form-group">
        <label for="memo">備考</title>
        <%= form.text_area :memo,{class:"form-control"} %>
    </div>
    <div class="form-group">
        <label for="title">進捗率</title>
        <%= form.text_field :status,{class:"form-control"} %>
    </div>
    <%= form.submit "変更を保存する" %>
<% end %>

<p class="link"><a href="/studies">&lt;&lt; ※トップページに戻る</a></p>

app/views/studies/index.html.erb
<div class="jumbotron">
<h1 class="display-4 text-s">学習記録アプリ</h1>

<table class="table">
  <thead>
    <tr>
      <th>日付</th>
      <th>学習した内容</th>
      <th>備考</th>
      <th>進捗率</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @studies.each do |study| %>
      <tr>
        <td width="200px"><%= study.date %></td>
        <td width="200px"><%= study.title %></td>
        <td width="300px"><%= study.memo %></td>
        <td width="100px"><%= study.status %>％</td>
        <td width="20px"><progress max="100" value="<%= study.status %>"></progress></td>
        <td width="150px">
        <button type="button" class="btn btn-outline-success">
          <%= link_to '編集する',study, method: :edit %>
        </button>
        </td>
        <td width="150px">
        <button type="button" class="btn btn-outline-danger">
          <%= link_to '削除する',study, method: :delete %>
        </button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<button type="button" class="btn btn-warning">
  <%= link_to '新しい学習項目を追加する', new_study_path %>
</button>
</div>

app/views/studies/new.html.erb
<h1 class="display-4 text-primary">新しく学習内容を記録する</h1>

<%= form_for(@study, rul:{controller:'studies',action:'new'}) do |form| %>
    <div class="form-group">
        <label for="date">日付</title>
        <%= form.text_field :date,{class:"form-control"} %>
    </div>
    <div class="form-group">
        <label for="title">学習した内容</title>
        <%= form.text_field :title,{class:"form-control"} %>
    </div>
    <div class="form-group">
        <label for="memo">備考</title>
        <%= form.text_area :memo,{class:"form-control"} %>
    </div>
    <div class="form-group">
        <label for="title">進捗率</title>
        <%= form.text_field :status,{class:"form-control"} %>
    </div>
    <%= form.submit "保存する" %>
<% end %>

<p class="link"><a href="/studies">&lt;&lt; ※トップページに戻る</a></p>

app/views/studies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @study.date %>
</p>

<p>
  <strong>Title:</strong>
  <%= @study.title %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @study.memo %>
</p>

<p>
  <strong>Status:</strong>
  <%= @study.status %>
</p>

<%= link_to 'Edit', edit_study_path(@study) %> |
<%= link_to 'Back', studies_path %>